FEATURE_VERSION = "feature_v002"

FEATURE_COLUMNS = [
    "timestamp",
    "method",
    "endpoint",
    "endpoint_template",
    "status_code",
    "response_time_ms",
    "query_parameter_count",
    "request_size_bytes",
    "response_size_bytes",
    "authenticated",
    "user_id_hash",
    "session_id_hash",
    "source_ip_hash",
    "user_agent",
    "user_profile",
    "ip_request_count_window",
    "unique_users_per_ip",
    "unique_endpoints_per_ip",
    "is_authentication_request",
    "login_attempt_count",
    "login_failure_count",
    "login_success_count",
    "login_failure_ratio",
    "unique_usernames_attempted",
    "requests_last_5s",
    "requests_last_10s",
    "requests_last_30s",
    "requests_last_60s",
    "requests_last_5m",
    "unique_endpoints_last_60s",
    "unique_objects_accessed_last_60s",
    "object_access_rate",
    "sequential_object_ratio",
    "object_id_entropy",
    "endpoint_entropy",
    "request_interval_mean",
    "request_interval_std",
    "session_request_count",
    "session_duration_seconds",
    "status_4xx_ratio",
    "status_5xx_ratio",
    "status_401_ratio",
    "status_403_ratio",
    "hour_of_day",
    "day_of_week",
    "time_since_previous_request",
    "burst_score",
    "traffic_label",
    "attack_type",
    "scenario_id"
]

ML_FEATURE_COLUMNS = [
    c for c in FEATURE_COLUMNS if c not in ("traffic_label", "attack_type", "scenario_id")
]
